# Generated by Django 4.1.5 on 2023-10-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_firstname_alter_customuser_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sso_type",
            field=models.CharField(max_length=10),
        ),
    ]
